[user_parameters]
debug = true
use_uv = true

excluded = [".venv", "__init__", "__pycache__"]
excluded_functions = ["wrapper"]

common_symbol = "●"
bad_symbol = "✗"
warning_symbol = "⚠"
good_symbol = "✔"
special_symbol = "★"
epic_symbol = "♥"
skipped_symbol ="…"
    
common_color = "white"
bad_color = "red"
warning_color = "dark_orange"
good_color = "green"
special_color = "yellow"
epic_color = "purple"
skipped_color ="gray"


[requires_v1]
special = ["Keyword arguments", "Args", "Parameters", "Attributes", "Keyword arguments:", "Args:", "Parameters:", "Attributes:", ":param", ":type"]
epic = ["Returns", "Raises", "Returns:", "Raises:", ":returns", ":rtype", ":raises"]

[requires_v2]
special = ["Keyword arguments:", "Args:", "Parameters:", "Attributes:", "Keyword arguments", "Args", "Parameters", "Attributes", ":param", ":type"]
epic = ["Returns:", "Raises:", "Usage:", "Examples:", "Returns", "Raises", "Usage", "Examples", ":returns", ":rtype", ":raises"]

[requires_v3]
special = ["Keyword arguments:", "Args:", "Parameters:", "Attributes:", "Keyword arguments", "Args", "Parameters", "Attributes", ":param", ":type"]
epic = ["Returns:", "Yields:", "Raises:", "Usage:", "Examples:", "Returns", "Yields", "Raises", "Usage", "Examples", ":returns", ":rtype", ":raises"]