[user_parameters]
excluded = [".venv", "__init__", "__pycache__"]
excluded_functions = ["wrapper"]

bad_symbol = "✗"
warning_symbol = "⚠"
good_symbol = "✔"
special_symbol = "★"
epic_symbol = "♥"

white_color = "white"
bad_color = "red"
warning_color = "dark_orange"
good_color = "green"
special_color = "yellow"
epic_color = "purple"

[requires_v1]
special = ["Keyword arguments", "Args", "Parameters", "Attributes", "Keyword arguments:", "Args:", "Parameters:", "Attributes:", ":param", ":type"]
epic = ["Returns", "Raises", "Returns:", "Raises:", ":returns", ":rtype", ":raises"]

[requires_v2]
special = ["Keyword arguments:", "Args:", "Parameters:", "Attributes:", "Keyword arguments", "Args", "Parameters", "Attributes", ":param", ":type"]
epic = ["Returns:", "Raises:", "Usage:", "Examples:", "Returns", "Raises", "Usage", "Examples", ":returns", ":rtype", ":raises"]
